# Generated by Django 3.2.11 on 2022-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220112_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptsIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=34, verbose_name='Receipt UID')),
                ('owner', models.CharField(max_length=100, verbose_name='Owner')),
            ],
        ),
    ]
