# Generated by Django 3.2.11 on 2022-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cash_register_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='created_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='dic',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='free_tax_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='ic_dph',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='items',
            name='issue_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='okp',
            field=models.CharField(blank=True, max_length=44),
        ),
        migrations.AlterField(
            model_name='items',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='pkp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='receipt_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax_base_basic',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax_base_reduced',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='total_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='type_receipt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_amount_basic',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_amount_reduced',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_rate_basic',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_rate_reduced',
            field=models.IntegerField(blank=True),
        ),
    ]
