# Generated by Django 3.2.11 on 2022-01-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220112_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='free_tax_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price_per_all',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='price_per_one',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax_base_basic',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax_base_reduced',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='total_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_amount_basic',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_amount_reduced',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_rate_basic',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='vat_rate_reduced',
            field=models.FloatField(blank=True),
        ),
    ]
