# Generated by Django 3.2.11 on 2022-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220112_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='item_pretty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='item_sub_class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
