# Generated by Django 3.2.11 on 2022-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20220119_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_class',
            field=models.CharField(blank=True, default='Bez kategorie', max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_sub_class',
            field=models.CharField(blank=True, default='Bez podkategorie', max_length=100),
        ),
    ]
