# Generated by Django 3.2.11 on 2022-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20220120_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_class',
            field=models.CharField(blank=True, default='Bez kategórie', max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_sub_class',
            field=models.CharField(blank=True, default='Bez podkategórie', max_length=100),
        ),
    ]
