# Generated by Django 3.2.11 on 2022-01-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220120_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_class',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_sub_class',
        ),
        migrations.AddField(
            model_name='receiptsids',
            name='date_of_purchase_time_stamp',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_of_purchase_time_stamp',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='SubCategory_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.category')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category'),
        ),
        migrations.AddField(
            model_name='items',
            name='sub_category_01',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.subcategory_01'),
        ),
    ]
