# Generated by Django 3.2.11 on 2022-01-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_category_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name2',
        ),
    ]
